config/routes.rb
Rails.application.routes.draw do

  match 'reports/present' => 'reports#present', via: [:get]
  resources :reports

  devise_for :users, controllers: { registrations: 'registrations' }
  namespace :admin do
    resources :users
  end

  root :to => 'home#index'

end

app/models/report.rb
class Report < ActiveRecord::Base

  belongs_to :user

  has_many :achievements, -> { order 'achievements.id' }
  accepts_nested_attributes_for :achievements, limit: 3, allow_destroy: true

  has_many :tasks, -> { order 'tasks.id' }
  accepts_nested_attributes_for :tasks, limit: 3, allow_destroy: true

  validates_presence_of :user, :excited, :jelly, :today, :previous_day
  validates_uniqueness_of :today, :scope => [:user_id]

  # Support roles
  resourcify

  extend SimpleCalendar
  has_calendar attribute: :today

  # Set dates on object creation
  after_initialize do
  	if new_record?
  		self.today ||= Date.today
  		# ensure we have exactly 3 achievements and 3 tasks
  		while self.achievements.length < 3
  			self.achievements << Achievement.new
  		end
  		while self.tasks.length < 3
  			self.tasks << Task.new
  		end
  	end
  end

  # Ensure the nested attributes are included in hash representations
  def as_json(options={})
  	j = super(options)
  	j[:achievements] = self.achievements
  	j[:tasks] = self.tasks
  	j
  end

  # Find the next and previous reports in the current meeting
  def next_prev
    reports = Report.where(:today => today).order(:created_at).to_a
    index = reports.index(self)
    {
      :next => (index < reports.length ? reports[index+1] : nil),
      :prev => (index > 0 ? reports[index-1] : nil)
    }
  end

  # The report for the previous working day for this user, if there is
  # one (nil otherwise)
  def previous_day_report
    Report.where(:today => today.go_back_by_weekdays(1),
                 :user_id => user).first
  end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  before_action :set_report, only: [:show, :edit, :update, :destroy]
  
  before_filter :authenticate_user!
  load_and_authorize_resource

  # GET /reports
  # GET /reports.json
  def index
    if params[:date]
      @date = Date.parse(params[:date])
      @reports = Report.where(:today => @date).order(:created_at)
      render :date_index and return
    elsif params[:user]
      @user = User.find(params[:user])
      # Just get the relevant reports for this view of the calendar
      range = SimpleCalendar::MonthCalendar.new(self).date_range
      @reports = Report.where(user_id: @user, today: range)
      render :user_index and return
    else
      range = SimpleCalendar::MonthCalendar.new(self).date_range
      @reports = Report.where(today: range)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reports }
    end
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    np = @report.next_prev
    @next = np[:next]; @prev = np[:prev]

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @report }
    end
  end

  # GET /reports/present?date=2015-06-07
  def present
    @date = Date.parse(params[:date])
    @reports = Report.where(today: @date).order(:created_at)
    render :present, layout: 'present'
  end
  
  # GET /reports/new
  # GET /reports/new.json
  def new
    @report = Report.new
    @report.user ||= current_user

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @report }
    end
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)
    @report.user ||= current_user

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render json: @report, status: :created, location: @report }
      else
        format.html { render action: "new" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reports/1
  # PUT /reports/1.json
  def update
    @report.user ||= current_user

    respond_to do |format|
      if @report.update_attributes(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy

    respond_to do |format|
      format.html { redirect_to reports_url }
      format.json { head :no_content }
    end
  end

  private

  def set_report
    @report = Report.find(params[:id])
  end

  def report_params
    params.require(:report).permit(:excited, :help_needed, :jelly, :today, :previous_day, achievements_attributes: [:id, :text, :_destroy], tasks_attributes: [:id, :text, :_destroy])
  end
  
end

app/helpers/reports_helper.rb
module ReportsHelper

  # Coordinates of the jelly babies 1-23 on the diagram
  def jelly_coords
    %w{15,3,103,133 135,45,197,163 212,14,329,88 349,0,403,36
       516,0,576,95 249,174,277,213 401,118,452,246 510,160,577,295
       42,201,92,298 169,255,219,358 217,255,263,358 311,288,393,410
       76,451,130,573 130,449,171,583 201,416,277,528 525,405,601,560
       343,495,414,633 43,713,139,812 144,640,248,758 266,656,322,780
       321,708,354,832 427,673,499,792 406,809,533,857}
  end

  # Text representing the given date with reference to the specified reference date, 
  # e.g. "On Wednesday" or "Yesterday"
  def date_text(date, reference_date)
    if date == reference_date
      "today"
    elsif date == reference_date - 1
      "yesterday"
    elsif date > reference_date - 7
      "on #{date.strftime '%A'}"
    else
      "on #{date.strftime '%e %b'}"
    end
  end
  
end

app/views/reports/_form.html.haml
- if @report.previous_day_report
  - @report.previous_day ||= @report.previous_day_report.today
= semantic_form_for @report do |f|
  .row
    .col-md-12
      - if @report.errors.any?
        .alert.alert-danger
          %strong Errors found:
          See below for details.
      = f.inputs :name => 'Dates' do
        .well Please ensure the dates below are correct for this report.
        = f.input :today, as: :string, input_html: {class: 'datepicker', value: (f.object.today.try(:strftime, '%Y-%m-%d'))}
        = f.input :previous_day, as: :string, input_html: {class: 'datepicker', value: (f.object.previous_day.try(:strftime, '%Y-%m-%d'))}
      = f.inputs :name => 'Headline' do
        .well
          This is a chance to tell the team what you're most excited about right now.
          %br
          It doesn't have to be work-related!
        = f.input :excited
      = f.inputs :name => 'Jelly baby' do
        .well Click the jelly baby that best describes your current mood.
        - if f.semantic_errors :jelly
          .alert.alert-error= f.semantic_errors :jelly
        = f.input :jelly, :as => :select, :collection => (1..23)
        = render 'jelly', :jelly => @report.jelly, :css => (@report.errors[:jelly].any? ? 'jelly jelly-error':'jelly')
        %map{:name => "jelly-map"}
          - jelly_coords.each_with_index do |c,i|
            %area{:coords => c, :id => "jelly-#{i+1}", :shape => "rect"}
      = f.inputs :name => %q{Previous day's achievements} do
        .well
          Choose the three things you did on your previous working day that you are most proud of.
          %br
          Everyone achieves more than three things in a day - just pick the top three!
        = f.fields_for :achievements do |achievement|
          - i = achievement.index.succ
          .input-group
            %span.input-group-addon{id: "achievement-#{i}-addon"}= i
            = achievement.input :text, label: false, aria: {describedby: "achievement-#{i}-addon"}
        - if @report.previous_day_report
          .well#previous-tasks
            A reminder of your tasks from #{link_to date_text(@report.previous_day_report.today,@report.today), report_path(@report.previous_day_report)}:
            %ol.enumerate
              - @report.previous_day_report.tasks.each do |task|
                %li= task.text
      = f.inputs :name => %q{Today's tasks} do
        .well
          Choose the three things you would most like to achieve today.
        = f.fields_for :tasks do |task|
          - i = task.index.succ
          .input-group
            %span.input-group-addon{id: "task-#{i}-addon"}= i
            = task.input :text, label: false, aria: {describedby: "task-#{i}-addon"}
      = f.inputs :name => %q{Other} do
        .well
          If any of your tasks can be more easily achieved with help from someone else, here is the place to mention that.
        = f.input :help_needed, :input_html => {:rows => 3}
  .form-actions
    = f.actions do
      = f.action :submit, button_html: {class: 'btn btn-default'}
      = f.action :cancel, label: 'Cancel', button_html: {class: 'btn btn-default'}

app/views/reports/_jelly.html.haml
- css ||= 'jelly'
=image_tag("jelly_babies/#{jelly || 0}.png", :alt => "Jelly baby #{jelly || 'not set'}", :class => css, :id => 'jelly-image', :usemap => '#jelly-map')

app/views/reports/_report_text.html.haml
.report-text
  %h2 I am most excited about:
  %p#excited= markdown report.excited
  %h2= "#{date_text(report.previous_day,report.today).titleize} I achieved:"
  %ol#achievements
    - report.achievements.each do |achievement|
      %li= achievement.text
  %h2= "Today I plan to achieve:"
  %ol#tasks
    - report.tasks.each do |task|
      %li= task.text
  %h2 Who can help me?
  #help_needed= markdown(report.help_needed, nl2br=true)

app/views/reports/by_day.html.haml
= content_for :title do
  Reports - all

.row
  .col-md-12
    %h1 All reports

.row
  .col-md-12#calendar
    = month_calendar events: @reports, table: {class: 'table table-bordered'} do |date, reports|
      .inner
        %b= date.strftime("%d")
        - if reports.count > 0
          .link
            = link_to pluralize(reports.count, 'report'), reports_path(date: date)

app/views/reports/date_index.html.haml
= content_for :title do
  Reports - #{@date}

.row
  .col-md-12
    %h1 Reports for #{@date.to_s :display}
    
- if @reports.any?
  .row
    .col-md-12
      = link_to reports_present_path(date: @date), class: 'btn btn-primary', id: 'present' do
        = glyph 'eye-open'
        Present
  .row
    .col-md-12
      %ul#reports-index
        - @reports.each do |report|
          %li
            = gravatar_for report.user, 16
            = link_to report.user.name, report_path(report)
- else
  .alert.alert-block.alert-warn
    %h4.alert-heading No reports to show!

app/views/reports/edit.html.haml
- model_class = @report.class
%h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/reports/index.html.haml
= content_for :title do
  Reports - all

.row
  .col-md-12
    %h1 All reports

.row
  .col-md-12#calendar
    = month_calendar events: @reports, table: {class: 'table table-bordered'} do |date, reports|
      .inner
        %b= date.strftime("%d")
        - if reports.count > 0
          .link
            = link_to pluralize(reports.count, 'report'), reports_path(date: date)

app/views/reports/new.html.haml
- model_class = @report.class
%h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/reports/present.html.haml
= content_for :title do
  Meeting for #{@date}
%section
  %h1 Daily meeting
  %h2= @date.to_s :display
- @reports.each do |report|
  %section.report
    %h2.title
      = gravatar_for report.user, 64
      = report.user.name
    .left
      = render 'jelly', jelly: report.jelly
    .right
      = render 'report_text', report: report
%section
  %h1 The end
  = link_to 'Back to app', reports_path(date: @date)

app/views/reports/show.html.haml
- model_class = @report.class

.row
  .col-md-12
    %h1
      = gravatar_for @report.user
      = @report.user.name
      %small= @report.today.to_s(:display)
.row
  .col-xs-6
    %a.btn.btn-default{id: 'prev', class: @prev ? '':'disabled', href: @prev ? url_for(@prev) : nil, role: 'button'}
      = glyph 'chevron-left'
      Previous
  .col-xs-6
    %a.btn.btn-default.pull-right{id: 'next', class: @next ? '':'disabled', href: @next ? url_for(@next) : nil, role: 'button'}
      Next
      = glyph 'chevron-right'
  
.row
  .col-md-6.col-xs-12
    = render 'jelly', :jelly => @report.jelly
  .col-md-6.col-xs-12
    = render 'report_text', :report => @report

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), reports_path, :class => 'btn btn-default'
  - if can? :update, @report
    = link_to t('.edit', :default => t("helpers.links.edit")), edit_report_path(@report), :class => 'btn btn-default'
  - if can? :destroy, @report
    = link_to t('.destroy', :default => t("helpers.links.destroy")), report_path(@report), :method => "delete", :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-danger'

app/views/reports/user_index.html.haml
= content_for :title do
  Reports - #{@user.name}

.row
  .col-md-12
    %h1
      = gravatar_for @user
      #{@user.name}'s reports
.row
  .col-md-12#calendar
    = month_calendar events: @reports, 
        table: {class: 'table table-bordered'},
        next_link: ->(param, date_range) { link_to raw("&raquo;"), {param => date_range.last.next_day, user: @user} },
        previous_link: ->(param, date_range) { link_to raw("&laquo;"), {param => date_range.first.prev_day, user: @user} } do |date, reports|
      .inner
        %b= date.strftime("%d")
        - if reports.first
          .link
            = link_to 'report', report_path(reports.first)