config/routes.rb
Rails.application.routes.draw do

  match 'reports/present' => 'reports#present', via: [:get]
  resources :reports

  devise_for :users, controllers: { registrations: 'registrations' }
  namespace :admin do
    resources :users
  end

  root :to => 'home#index'

end

app/views/layouts/_alerts.html.haml
- if notice
  %p.alert.alert-info
    %button.close{'data-dismiss' => 'alert'} x
    = notice
- if alert
  %p.alert.alert-danger
    %button.close{'data-dismiss' => 'alert'} x
    = alert

app/views/layouts/_head.html.haml
- app ||= 'application'
%meta{:charset => "utf-8"}/
%meta{'http-equiv' => 'X-UA-Compatible', content: 'IE=edge'}/
%meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
%title= content_for?(:title) ? "#{yield(:title)} - Jelly" : "Jelly"
= csrf_meta_tags
= favicon_link_tag '/favicon.ico'
= stylesheet_link_tag app, media: 'all', 'data-turbolinks-track' => true
= stylesheet_link_tag '//fonts.googleapis.com/css?family=Chewy', media: 'all'
= javascript_include_tag app, 'data-turbolinks-track' => true
%link{:href => "images/logo.png", :rel => "apple-touch-icon"}/
%link{:href => "images/logo-72.png", :rel => "apple-touch-icon", :sizes => "72x72"}/
%link{:href => "images/logo-114.png", :rel => "apple-touch-icon", :sizes => "114x114"}/

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{type: 'button', data: {toggle: 'collapse', target: '#navbar-content'}}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Jelly', root_url, class: 'navbar-brand'
    .collapse.navbar-collapse#navbar-content
      %ul.nav.navbar-nav
        - if current_user
          %li
            = link_to new_report_path do
              = glyph 'file'
              Write report
          %li.dropdown
            %a.dropdown-toggle{data: {toggle: 'dropdown'}, role: 'button', aria: {expanded: false}}
              = glyph 'eye-open'
              View reports
              %b.caret
            %ul.dropdown-menu
              %li
                = link_to reports_path :date => Date.today do
                  = glyph 'eye-open'
                  Today's reports
              %li
                = link_to reports_path :user => current_user do
                  = glyph 'user'
                  My reports
              %li
                = link_to reports_path do
                  = glyph 'calendar'
                  All reports
      %ul.nav.navbar-nav.navbar-right
        %li.dropdown
          %a.dropdown-toggle{data: {toggle: 'dropdown'}, role: 'button', aria: {expanded: false}}
            - if user_signed_in?
              = gravatar_for current_user, 16
              %span.username= current_user.name
            - else
              Not signed in
            %b.caret
          %ul.dropdown-menu
            - if user_signed_in?
              - if current_user.has_role? :admin
                %li= link_to 'Admin', admin_users_path
              %li= link_to 'Account', edit_user_registration_path
              %li= link_to 'Logout', destroy_user_session_path, :method => :delete
            - else
              %li= link_to 'Login', new_user_session_path
              %li= link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    = render 'layouts/head'
  %body
    .wrapper
      = render 'layouts/navbar'
      .container-fluid{class: params[:controller]}
        = render 'layouts/alerts'
        = yield
      .push
    %footer
      %p
        &copy; 2012-2015 Fish Percolator #{link_to "[github]", "https://github.com/fishpercolator/jelly"}
        %br
        &copy; #{link_to "Trainer Bubble", "http://www.trainerbubble.com/"} (Jelly Baby Tree). Used with permission.

app/views/layouts/present.html.haml
!!!
%html{:lang => "en"}
  %head
    = render partial: 'layouts/head', locals: {app: 'present'}
  %body
    .reveal
      .slides
        = yield
    :javascript
      Reveal.initialize({
        controls: false,
        progress: true,
        history: true,
        center: true,
        transition: 'slide',
        theme: 'white',
        zoomKey: 'ctrl',
        dependencies: [
          { src: '#{javascript_path('zoom')}', async: true }
        ]  
      });